using Serene.BasicSamples.Pages;
using Serenity.Navigation;

[assembly: NavigationMenu(7950, "Basic Samples/Grids")]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Cancellable Bulk Action", typeof(BasicSamplesController), action: "CancellableBulkAction")]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Conditional Formatting", typeof(BasicSamplesController), action: "ConditionalFormatting")]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Custom Links In Grid", typeof(BasicSamplesController), action: "CustomLinksInGrid")]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Drag & Drop in Tree Grid", typeof(BasicSamplesController), action: "DragDropInTreeGrid")]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Enabling Row Selection", typeof(BasicSamplesController), action: "EnablingRowSelection")]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Grouping and Sum. In Grid", typeof(BasicSamplesController), action: "GroupingAndSummariesInGrid")]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Grid Filtered by Criteria", typeof(BasicSamplesController), action: "GridFilteredByCriteria")]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Initial Value for Quick Flt.", typeof(BasicSamplesController), action: "InitialValuesForQuickFilters")]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Inline Action Buttons", typeof(BasicSamplesController), action: "InlineActionButtons")]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Inline Image In Grid", typeof(BasicSamplesController), action: "InlineImageInGrid")]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Product Excel Import", typeof(BasicSamplesController), action: "ProductExcelImport")]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Quick Filter Customization", typeof(BasicSamplesController), action: "QuickFilterCustomization")]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Removing Add Button", typeof(BasicSamplesController), action: "RemovingAddButton")]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Stored Procedure Grid", typeof(BasicSamplesController), action: "StoredProcedureGrid")]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Tree Grid", typeof(BasicSamplesController), action: "TreeGrid")]
[assembly: NavigationLink(7950, "Basic Samples/Grids/View Without ID", typeof(BasicSamplesController), action: "ViewWithoutID")]
[assembly: NavigationLink(7950, "Basic Samples/Grids/Visual Studio Gallery Q & A", typeof(BasicSamplesController), action: "VSGalleryQA")]
